### ISSUE TITLE
Unable to change build action/related options: property value is not valid

### ISSUE THREAD

**Issue by SomeAnon42** [dotnet/project-system#1044]
Steps to reproduce:
1. Create a new C# project (in my case, it was a shared project)
2. Add an existing file ~~with a double extension~~ to the project (e.g. 'program.exe.vcdiff')
**3/7/2017:** the file extension doesn't really matter, I was able to repro this with _New Text Document.txt_
3. Try to rename it or change the build action **and** some other related property (e.g. _Copy to Output Directory_)

You may need to reload the solution and/or repeat the steps. Eventually, you should encounter this error.
After that, you won't be able to change the build action of *any* file in the project.
![bug](https://cloud.githubusercontent.com/assets/6377116/21504171/99fe3664-cc6d-11e6-9975-a78071a3591e.PNG)

**Comment by davkean** [comment]
Here's another (somewhat) strange repro:

Select a C# file
Create a new folder called "Foo"
Change Build Action from "C# compiler" -> "Context"
Fails with the same thing. If you don't create a folder in 2, it doesn't fail.

**Comment by RaulPerez1** [comment]
I'm unable to repro this using the latest build

**Comment by davkean** [comment]
Yep, can no longer repro this either.

**Comment by SomeAnon42** [comment]
Congrats on the release 😉 
Just repro'd this with the RTM bits. It wasn't really about double extensions. No matter the file name, it fails. This time I added an empty txt file to the project and tried to change build action to _Content_ then set _Copy to Output Directory_ to _Copy if newer_.
![image](https://cloud.githubusercontent.com/assets/6377116/23667705/d4b7d0ec-036f-11e7-8d26-5101aa9d083e.png)

**Details:**
`An error has occurred while saving the edited properties listed below:
	Copy to Output Directory
One or more values are invalid. Mismatched PageRule with the wrong ItemType.`

**Comment by davkean** [comment]
@SomeAnon42 Thanks for following up.

**Comment by davkean** [comment]
@srivatsn Do you want this for 15.2 or 15.3?

**Comment by tannergooding** [comment]
Looks like the rename isn't propagating all the way through and this may be specifically related to shared projects.

Specifically, I did the following:
* Create a new shared project
* Add a new text file
* Rename the text file to `T.txt` (I did this via the solution explorer)
* Attempt to modify the Copy to Output Directory property

This results in a number of exceptions being thrown:
 ```
"Could not find project item with item type 'Content' and include value 'C:\\Users\\tagoo\\documents\\visual studio 2017\\Projects\\SharedProject1\\SharedProject1\\TextFile1.txt'."
```
and
```
An error has occurred while saving the edited properties listed below:
	Copy to Output Directory
One or more values are invalid. Could not find project item with item type 'Content' and include value 'C:\Users\tagoo\documents\visual studio 2017\Projects\SharedProject1\SharedProject1\TextFile1.txt'.
```

The *.shproj is not modified (as expected), but the *.projitems is also not modified and still has `<None Include="$(MSBuildThisFileDirectory)New Text Document.txt" />`, not sure if that is expected (at the very least, I would expect `Content` and not `None`, since `Content` is what is listed in the properties page by default).

**Comment by SomeAnon42** [comment]
@tannergooding I can reproduce this with other project types as well (specifically, .NET Core and .NET Standard projects). Recorded a video, just in case.
![2017-03-29_00-11-57](https://cloud.githubusercontent.com/assets/6377116/24427697/96bc1d74-1414-11e7-85a0-64f661773af2.gif)

**Comment by tannergooding** [comment]
Ok, I am able to repro that as well.

It is interesting that we aren't setting the correct output type here, when it is defined in our `ProjectItemsSchema.xaml` to be:
```
<ContentType
        Name="Text"
        DisplayName="Text file"
        ItemType="Content">
    </ContentType>
```
and
```
<FileExtension Name=".txt" ContentType="Text" />
```

**Comment by wayoung** [comment]
Yeah, this is happening to me in production. Did a port from VS2015 to VS2017 with the new .csproj .NETCore files. Everything changed. This is one of the mucky errors.

**Comment by kierenj** [comment]
I'm adding a new JSON file to a test project, then trying to change Copy to Output Directory (to anything) and I get:

An error has occurred while saving the edited properties listed below:
	Copy to Output Directory
One or more values are invalid. Mismatched PageRule with the wrong ItemType.

Is this the same issue?

**Comment by davkean** [comment]
Yes it's the same issue. @jviau is this one of the ones you fixed for 15.3?

**Comment by jviau** [comment]
@davkean yes this looks exactly like an issue I fixed for 15.3. [Bug 397479](https://devdiv.visualstudio.com/DevDiv/VS%20IDE%20CPS/_workitems?id=397479&_a=edit&triage=true)

**Comment by srivatsn** [comment]
Thanks @jviau - @tannergooding mentioned that he isn't able to repro this anymore as well.

**Comment by kierenj** [comment]
@srivatsn Humm.  Would you mind letting me/us know what the above means, in terms of how/when we might get a fix we can install, please?

**Comment by srivatsn** [comment]
This fix will be in the next Preview of 15.3 which should be coming out soon.

**Comment by azjerei** [comment]
When is this becoming available in a release? I am experiencing this issue right now with .NET Standard 2.0.

**Comment by azjerei** [comment]
@Pilchie Build of what?

**Comment by Pilchie** [comment]
Visual Studio - can you let us know the build number from "Help - About"?

**Comment by azjerei** [comment]
Visual Studio is at 15.4.3.

**Comment by Pilchie** [comment]
@azjerei - it sounds like you're hitting a slightly different bug with similar symptoms then.  Can you share a repro project where this happens?

**Comment by azjerei** [comment]
@Pilchie Check out this example application where the problem can be found: https://1drv.ms/u/s!Aiutb3QYc1ScmbBC0qC7WVzIXuECLw

**Comment by Pilchie** [comment]
@azjerei Both of the projects in that fail to load because of:

`<Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), Standard.targets))\Standard.targets" />`

for me:

`D:\Dumps\1044\CodeAnalysis\CodeAnalysisLib\CodeAnalysisLib.csproj : error  : The imported project "C:\Standard.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\Dumps\1044\CodeAnalysis\CodeAnalysisLib\CodeAnalysisLib.csproj`

**Comment by azjerei** [comment]
@Pilchie Ah, that's unfortunate. But, I made a simple console app that should not have that problem, but that reproduces the problem in this thread: https://1drv.ms/u/s!Aiutb3QYc1ScmbBFYOjZrNCN_J1JUQ

**Comment by Pilchie** [comment]
Unfortunately, I'm not able to repro that with either the 15.4.5 build or the 15.5 Preview 5 build.

@davkean have you got ideas on how to figure out what's going on here?

**Comment by davkean** [comment]
Sound like @jviau refresh which he added in 15.3 isn't working, @azjerei can you record a video like @SomeAnon42 did to show exactly the steps that are occurring?

**Comment by azjerei** [comment]
@davkean Here is a GIF showing the steps: https://1drv.ms/i/s!Aiutb3QYc1ScmbMFay50zRBbfVaJMQ

**Comment by davkean** [comment]
Thanks that perfectly describes why I couldn't repro it - I was using Properties tool window.

This has been fixed in 15.6 with: https://github.com/dotnet/project-system/pull/2984. As a workaround, use the Properties _tool window_ to change properties ( View -> Properties Window) instead of Properties pages.

**Comment by azjerei** [comment]
Awesome! Thanks for everything.

**Comment by stas-lucky** [comment]
This issues still exists. Mentioned issue by @SomeAnon42 (video) above is reproducible on my VS. Attached screenshot with VS version (15.6.0 Preview 2.0).  

I came to this issue conversation while was searching for solution with properties window. Thanks, workaround with Properties tool window helped.

![image](https://user-images.githubusercontent.com/6118178/35333460-85bb231c-0117-11e8-9c3d-4ba605cd4419.png)
![image](https://user-images.githubusercontent.com/6118178/35333573-ddf16f00-0117-11e8-8272-8fbcf5e5c4d0.png)

**Comment by tudorsibiu90** [comment]
I am still experiencing the same thing with version 15.6.1 of Visual Studio Professional 2017.
Is there a workaround or something?

**Comment by Pilchie** [comment]
@tudorsibiu90 Change through the properties tool window, instead of the modal properties dialog.  Select the file and press F4 to get the properties window.

**Comment by wooderz** [comment]
Having the same issue here, can confirm the properties tool (F4) rather than the Properties dialog (Right Click > Properties) works.

I assume weirdly they are using different mechanisms

**Comment by R08** [comment]
WTF

**Comment by FabriDamazio** [comment]
@wooderz  i can reproduce the same situation.

As workaround i selected the file and pressed F4 and changed what i needed

**Comment by davkean** [comment]
We've fixed this inconsistently in 15.8. Only F4 properties now shows.

**Comment by jakesays** [comment]
I'm still getting this with 15.8 - I added a .resx file to a core 2.0 project, set the build action to Embedded resource and the custom tool to ResXFileCodeGenerator. when I click ok, i get that error.

**Comment by davkean** [comment]
@jakesays Can you please file a new bug with the exact steps you took to get the error?
