### ISSUE TITLE
Improve PackageReference support in old project system

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#2129]
Currently the APIs for accessing PackageReference information (that is, the `VSProject4` and `PackageReferences` interfaces) operate more-or-less right on top of the project file's XML. This is limiting in that the PackageReference elements will not have been evaluated; for example, if the `Version` metadata refers to a property such as `$(MyCommonVersion)` then what a consumer of these interfaces will see is the literal string "$(MyCommonVersion)" rather than the evaluated value.

We should update these interfaces to work on the evaluated data instead.

**Comment by AArnott** [comment]
Note the title of this issue says "old" project system, but this is happening with the new .NET SDK project system.

**Comment by davkean** [comment]
@AArnott What do you mean? We use the evaluated value in the new project system.

**Comment by AArnott** [comment]
I have solution of only new project system projects, and yet NuGet/Home#5295 (which was closed as a dupe of this one) occurs in these solutions.

**Comment by davkean** [comment]
Can you give me a repro? Make note that @onovotny's repro has a extraneous single quotes around the value.

**Comment by davkean** [comment]
This works fine:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <GiveMeAVersion>9.0.1</GiveMeAVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(GiveMeAVersion)" />
  </ItemGroup>
</Project>
```

**Comment by AArnott** [comment]
Try moving the ref to directory.build.props. Restore is fine, but every time you build in VS or run tests, the error appears in the output window.

**Comment by davkean** [comment]
I can still not repro this - I pulled it out into Directory.Build.props, installed xunit, ran tests with zero issue. In the new project system we read all package references using evaluation, so something else must be involved.

Given this is tracking legacy project system support, can you file a new bug with a repro?

**Comment by AArnott** [comment]
I'll find or recreate a repro to share in the next day or two.

**Comment by tmeschter** [comment]
Doesn't meet the bar for 15.5; moving out.

**Comment by AArnott** [comment]
OK, at least with my most recent repro, I see that it disappears when I remove the VSIX project from the solution, so it does indeed seem to be an issue with the old project system.

**Comment by AArnott** [comment]
BTW, this blocks running unit tests in affected solutions. It also causes the Solution Restore command to report failure and packages to not be restored.

**Comment by mwascher** [comment]
My team is encountering this issue with the latest version of VS 2017. Due to some of our legacy dependencies, we are unable to migrate our csproj files to use the new .NET SDK format, which I understand doesn't have this issue. 

Can we expect a fix for this issue to make it out in 15.6?

**Comment by venkatcmsft** [comment]
Any idea when this is expected to be fixed? (date?)

**Comment by Pilchie** [comment]
We do not have an ETA at this time.

**Comment by venkatcmsft** [comment]
Can you please prioritize this. kind of annoying defect.

**Comment by AmadeusW** [comment]
This error particularly affects VSTS users using authenticated feeds. 
Since the (authenticated) IDE restore broken, the only way to restore private packages is to go to a directory that contains `CredentialProvider.VSS.exe`, and use nuget there, passing in path to my project. This slows down our team's workflow.

**Comment by anangaur** [comment]
We have been receiving multiple customers (internal Microsoft and external) requests to make this work. 

We also want the ecosystem to move forward to start using PackageReference and this seems to be a blocker.

In addition, we are moving towards enabling credential provider support cross plat with dotnet.exe and msbuild.exe and these tools work with PackageReference. Our story will be broken without the variable replacement support.

Is it too late to take this in for 15.6?

**Comment by tmeschter** [comment]
Fixed in 15.9.

**Comment by bergmeister** [comment]
@tmeschter Using `15.9-preview3`, this still happens to me. You can repro by cloning the PowerShell repo [here ](https://github.com/PowerShell/PowerShell)and adding the [hosting.csproj](https://github.com/PowerShell/PowerShell/blob/master/test/hosting/hosting.tests.csproj) to [PowerShell.sln](https://github.com/PowerShell/PowerShell/blob/master/PowerShell.sln)

**Comment by tmeschter** [comment]
@bergmeister This bug concerns missing functionality in VS when working with _non_-SDK-based projects. If you're seeing errors while building or when using SDK-based projects (and it looks to me like you are) then that is a separate issue.
