### ISSUE TITLE
Intellisense does not refresh when a new file is created in VS

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/project-system#2292]
I've been having a weird issue with one of my projects recently. I'll be working on my project, and attempt to add a new file. When I do this, the file gets created, and if I write my code to use something in that new file it builds correctly. However, Intellisense sees anything in the new file as non existent until a VS restart. VS keeps giving me errors saying it cannot find a class, even though the build succeeds. If I restart VS, the problem goes away. Another oddity is even if I use the VS lightbulb menu to create the missing class in a new file, Intellisense doesn't detect that new file, and still keeps displaying the same error.

https://github.com/robotdotnet/NetworkTables

Here is the repo for my project.  Also attached below is a view of what my VS looks like when this error occurs.

![vswindow](https://cloud.githubusercontent.com/assets/7727148/26461923/9d11df00-4133-11e7-931c-a0c3254cf506.PNG)

**Comment by davkean** [comment]
@ThadHouse What version of Visual Studio are you running?

**Comment by davkean** [comment]
This smells like an issue we fixed in 15.1.

**Comment by ThadHouse** [comment]
I'll check my computer at home to see which version I have there. But I just tested my laptop, which has 15.1, and was able to reproduce the issue slightly differently. When adding the new class, it shows up properly for one of my target frameworks, but not the other target framework. 

![screenshot 14](https://cloud.githubusercontent.com/assets/7727148/26472971/9a21383e-415d-11e7-86f1-e377be3a601f.png)

**Comment by davkean** [comment]
@ThadHouse Yep, that's another issue that aware of and we've recently fixed.

**Comment by davkean** [comment]
I think that's made it into 15.3.

**Comment by ThadHouse** [comment]
Ok good to know. I'll report back with what my desktop is at when I get home. Glad to know the multiple frameworks issue is fixed.

**Comment by MattGertz** [comment]
(Moving this to 15.6 while @ThadHouse confirms, just for paperwork's sake as I try to get the high-view on 15.3 work remaining.  But please tag me and davkean if this still repos.)

**Comment by fubar-coder** [comment]
The same problem exists when moving a file. The target framework identifier (combo box at the top left corner of the edit window) shows "Miscellaneous files". The problem still exists in the latest 15.3 preview.

**Comment by davkean** [comment]
That's a known bug with renaming open files.

Sent from my Windows 10 phone

**Comment by anurse** [comment]
> That's a known bug with renaming open files.

Is that tracked somewhere? I'm see it very consistently and it's a major pain :)

**Comment by davkean** [comment]
Yes it's a giant pain, it's been fixed and should be in the latest VS builds.

**Comment by natidea** [comment]
Related instances of this reported on [VSFeedback](https://developercommunity.visualstudio.com/content/problem/68166/with-new-project-format-files-sometimes-appear-as.html)

**Comment by Pilchie** [comment]
Closing this, as we believe it should be fixed in recent builds.  Please let us know if you're still seeing it.
