### ISSUE TITLE
Up to date check problems with non-compilation files

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/project-system#2458]
Source items of type None or Content should only be checked against the outputs if they are copied to the output. If they are never copied, they can cause the check to fail spuriously.

**Comment by panopticoncentral** [comment]
Also when they *are* copied, they can cause problems because their date is not touched by the copy. So if you have a content file that is very old, it can cause the up to date check to fail because we see an output that is older than the newest input.

**Comment by srivatsn** [comment]
Fixed by #2484

**Comment by gulbanana** [comment]
The second part of the issue, about outdated dates, doesn't seem to be fixed. In 15.3 release I have projects failing up-to-date because of a CopyToOutputDirectory="PreserveNewest"

**Comment by gulbanana** [comment]
Oddly, I still see
`Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.`
in the actual build

**Comment by davkean** [comment]
@gulbanana Please file a new with the logs in the output window when turned on via Options -> Project and Solutions -> .NET Core -> Logging Level > Verbose.

**Comment by gulbanana** [comment]
Will do!

**Comment by gulbanana** [comment]
this logging is really good, it taught me that the problem is actually something slightly different..

**Comment by davkean** [comment]
Awesome!, Great to hear. //cc @panopticoncentral
