### ISSUE TITLE
Microsoft.VisualStudio.ProjectSystem.ProjectTreeCorruptionException: Failed to update the project tree when adding mvc view

### ISSUE THREAD

**Issue by timcromarty** [dotnet/project-system#2555]
Adding a MVC view generates the following error:
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectTreeCorruptionException: Failed to update the project tree. ---> System.ArgumentException: An item with the caption "_envelopesTable.cshtml" already exists in the tree with the same sort order as the item being added.
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(UnattachedProjectTreeNode node)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(IProjectTree subtree)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FixDependencyInFolder(IProjectTree tree, Dictionary`2 movingMapping)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.UpdateDynamicParentAfterAddedNewItems(IProjectTree folder, ImmutableDictionary`2 newItems)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AdoptDepedentItemsAfterAddingNewItems(IProjectTree folder, IImmutableDictionary`2 projectData, ImmutableDictionary`2 newItemsInFolder)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, IEnumerable`1 addedItems, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<>c__DisplayClass204_0.<ProjectSubscriptionService_ChangedAsync>b__0(IProjectVersionedValue`1 treeSnapshot, ConfiguredProjectExports configuredProjectExports, CancellationToken ct)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass68_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass70_0.<<SubmitTreeUpdateCoreAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.VisualStudio.ProjectSystem.ProjectTreeCorruptionException: Failed to update the project tree. ---> System.ArgumentException: An item with the caption "_envelopesTable.cshtml" already exists in the tree with the same sort order as the item being added.
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(UnattachedProjectTreeNode node)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(IProjectTree subtree)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FixDependencyInFolder(IProjectTree tree, Dictionary`2 movingMapping)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.UpdateDynamicParentAfterAddedNewItems(IProjectTree folder, ImmutableDictionary`2 newItems)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AdoptDepedentItemsAfterAddingNewItems(IProjectTree folder, IImmutableDictionary`2 projectData, ImmutableDictionary`2 newItemsInFolder)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, IEnumerable`1 addedItems, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<>c__DisplayClass204_0.<ProjectSubscriptionService_ChangedAsync>b__0(IProjectVersionedValue`1 treeSnapshot, ConfiguredProjectExports configuredProjectExports, CancellationToken ct)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass68_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass70_0.<<SubmitTreeUpdateCoreAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
Project: C:\Source\repos\Document Hub\src\Ssp.DocumentHub\Ssp.DocumentHub.csproj

**Comment by srivatsn** [comment]
Filed [a bug on CPS](https://devdiv.visualstudio.com/DevDiv/_workitems?id=469189&fullScreen=false&_a=edit) @lifengl @jviau please provide any updates here that you might have.

**Comment by viktorveis** [comment]
This is the same issue as here, but we don't have a local repro: https://developercommunity.visualstudio.com/content/problem/76063/microsoftvisualstudioprojectsystemprojecttreecorru.html

@timcromarty, could you please share exact repro steps, including steps to create a repro solution?

**Comment by jviau** [comment]
@timcromarty what build of VS is this occurring on? This looks like an issue we have fixed for 15.3.

**Comment by timcromarty** [comment]
This was happening on 15.3 preview 3, and is still occurring on 15.3 preview 4. Version 4.6.01055.

Sorry, I have not had time to create a repro
