### ISSUE TITLE
Intellisense for netstandard (<1.4) broken for 4.6.1 project (15.3 update 3)

### ISSUE THREAD

**Issue by kierenj** [dotnet/project-system#2660]
Hi - I've done a little searching and found links to #485, however I'm getting this with 15.3 update 3.

I have a .NET Standard class library project (netstandard13, but anything <netstandard16 has the issue), and a regular old .NET Framework 4.6.1 class library project.

The classes from the netstandard14 project show as red, with no intellisense.  Compilation is fine however.  There are no reference errors / warning triangles in the UI.  If I try netstandard15, netstandard16, or event net461, I get the same issue.

The netstandard14 project is using AutoRest-generated API client code, and references Microsoft.Rest.ClientRuntime, which needs netstandard14.

Strangely, if I change the netstandard14 project to netstandard13 or below, the intellisense issues disappear for types in the project itself, but then of course other errors crop up since the types it uses in the NuGet package are no longer available.

Is there anything I can do to diagnose further / help?

**Comment by kierenj** [comment]
A restart of my machine fixed this.  (Reloading the solution and restarting Visual Studio did not - it took a full restart).
My issue is fixed, but if this is something you'd like me to give more detail on, let me know.

**Comment by srivatsn** [comment]
@dsplaisted could this be the TargetPlatform issue you fixed recently?

**Comment by harvinders** [comment]
This is still an issue for me. Tried restarting, but that did not help.

**Comment by Gonnagle** [comment]
Are you using ReSharper? I had a similar issue with net461 unit test project testing a netstandard1.6 class library. In my case the issue seemed to be with ReSharper and I was able to fix it by installing the latest EAP version (2017.2 EAP 12, https://www.jetbrains.com/resharper/eap/). As a workaround also disabling ReSharper fixed the issue.

**Comment by davkean** [comment]
Thanks for the feedback, @kierenj Can you please check to see if you are using R#? If you aren't using R# can you provide a repro project? I'll reopen this bug if you can provide one.

**Comment by kierenj** [comment]
Hi, yes I was using ReSharper, but as I say, a machine restart fixed it, so I haven't encountered it again.  I'm not sure what else I can do to help, the project was very large and I can't share code from it.  I'm still subscribed to this thread so if anyone wants any other info (though I can't think what it would be), let me know.
