### ISSUE TITLE
Adding additional nuget sources through the property RestoreAdditionalProjectSources in a target are not picked up by Restore in Visual Studio

### ISSUE THREAD

**Issue by atanasa** [dotnet/project-system#2780]
I am using a target to register additional nuget package source like this:
```
  <Target Name="RegisterCustomPackageSource"
          BeforeTargets="_GetRestoreSettingsPerFramework">
	...
    <PropertyGroup>
      <RestoreAdditionalProjectSources>....</RestoreAdditionalProjectSources>
    </PropertyGroup>
  </Target>
```

When I run Restore from the command line, it works. When I do a Restore in Visual Studio it does not work. The sources listed in the log of the operation in Visual Studio does not include the additional source.

Is there any particular reason why the project system calls into the Restore operation through code rather than through MSBuild (as the cli restore does)?

**Comment by davkean** [comment]
Restore in VS is much harder than via the command-line, as you need to play nicely with UI and unsaved projects, hence why we don't "restore" via MSBuild.

This looks like a NuGet bug, this should be a dependency of CollectPackageReferences.

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#5842

**Comment by emgarten** [comment]
This property is sent as part of the nomination, it would be a bug on the project system side if this isn't sent.

Also, depending on CollectPackageReferences should fix this for VS.

**Comment by atanasa** [comment]
@emgarten Depending on CollectPackageReferences does not fix it. If the property is not set in a target but at the top level of the project it is picked up by the restore eventually.

As far as I understand the code, the nomination data source is the project not the CollectPackageReferences target for that property - [NuGetRestore.xaml](https://github.com/dotnet/project-system/blob/3c760034e97c2551a8ff98fe01e46830d34b4213/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml)

**Comment by atanasa** [comment]
Here is a sample project that uses CollectPackageReferences and reproduces this:
[NuGetSourceRepro.zip](https://github.com/dotnet/project-system/files/1284981/NuGetSourceRepro.zip)

**Comment by emgarten** [comment]
@davkean is there a way to set this property so that the project system reads it when it gathers the project metadata for restore nomination?

**Comment by natidea** [comment]
Since NuGetRestore.xaml does not wait on any targets, I think it reads properties from Evaluation.
One fix may be to do something similar to PackageReference.xaml and create a target that returns all the desired properties, including those ones that may have been set later as part of the DT build. But perhaps there is a simpler way to do this?
