### ISSUE TITLE
Support reloading targets/settings/props in legacy project system

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#2888]
Related to [490432](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/490432).

Currently, once an imported targets/settings/props/project file has been loaded by the legacy project system it will never be reloaded, even if it changes on disk. In the past imports generally came from MSBuild, VS, or the framework itself, and those would never change. A user could certainly create their own .targets project (or .props, etc.) and import it into their project, but this was rare enough that there wasn't a need to support editing that file while the project was open.

Now, however, NuGet generates *.nuget.g.props files under the obj directory to pull in the props/settings/etc. included in the packages. This generated file could change every time a package is added, removed, or updated. This can lead to weird or inconsistent behavior of various forms in the IDE until the solution is closed and re-opened, with no way for the user to know what has gone wrong.

We should support reloading these targets when we see them change on disk.

**Comment by davkean** [comment]
This is a non-trivial feature that will eat into time to get UWP over to the new project system. We'd previously scoped out from every doing this.

**Comment by Pilchie** [comment]
Moving to 15.7, as we're out of time to do this for 15.6

**Comment by Pilchie** [comment]
Moving to 15.8 - we have a prototype implementation, but the risk of introducing new UI delays is to great to take this late in 15.7.

**Comment by Pilchie** [comment]
Also reported at :link: https://developercommunity.visualstudio.com/content/problem/248037/defaultbuildprops-with-langversion-is-not-used-by.html - for `Directory.build.props` in that case.

**Comment by davkean** [comment]
@tmeschter We reload NuGet props/targets now in 15.8, right? We should leave this to tracking reloading other sorts of targets, in which case, this milestone looks incorrect.

**Comment by tmeschter** [comment]
That's correct; support for reloading the .props and .targets created by NuGet is in 15.8. Extending that to Directory.build.props/Directory.build.targets wouldn't be too hard.

**Comment by tmeschter** [comment]
Tom's triage notes: recommend we do nothing for this and close the issue.

**Comment by j3parker** [comment]
So this bug won’t be fixed? Where I work we have a workaround where we delete everyone’s .vs folders every time we change Dirctory.build.targets (which is pretty frequent, we use that to define common constants etc. ) which is pretty annoying for our developers

**Comment by j3parker** [comment]
Oh, this is only for the legacy project system. So it’s not a problem in the new one? We’re in the process of migrating now.

**Comment by tmeschter** [comment]
@j3parker I believe the new project system will automatically reload Directory.Build.props/.targets files that are next to a project file or in a subdirectory, but not those "above" the project in the file system (e.g. next to the solution). However, at this point we're much more likely to address that limitation of the new system than we are to make any changes in the old one.

**Comment by davkean** [comment]
Slight clarification, the new project-system will hot reload any targets file in the graph of the project. I use it all the time, we change this file https://github.com/dotnet/project-system/blob/master/build/Packages.targets which contains all the package versions across the solution and every project automatically picks it up while VS is open.

**Comment by tmeschter** [comment]
We have decided to _not_ implement this feature request for the legacy project system. Closing.

**Comment by j3parker** [comment]
Cool, thank you! Great news RE: the new project system. It totally makes sense to me that this wouldn't be fixed in the legacy one.

**Comment by jozefizso** [comment]
This is still not implemented in Visual Studio 2019 v16.9 it is just a pain to work with .props files as Visual Studio will use incorrect values during build because of this caching.

**Comment by kvenkatrajan** [comment]
@chipplyman  - we have informed the internal team supporting the legacy project system (just FYI this repo is for the sdk style project system). The recommendation is to open a VS feedback Suggestion Ticket (link : https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022) with the details of your scenario which would help immensely with prioritization. Thanks in advance!

CC: @ladipro

**Comment by chipplyman** [comment]
Several such tickets already exist
https://developercommunity.visualstudio.com/t/changes-to-props-files-dont-get-detected-or-reload/832265
https://developercommunity.visualstudio.com/t/defaultbuildprops-with-langversion-is-not-used-by/248037
https://developercommunity.visualstudio.com/t/visual-studio-directorybuildprops-caching/433497

**Comment by MikeFarrington** [comment]
This has been driving me crazy.  Every time I need to tweak my Directory.Build.props file I need to close Visual Studio, clear the .vs cache folder, then re-launch.  Not only that, if I make a mistake in formatting the file, which contains my BaseIntermediateOutputPath and BaseOutputPath settings, I then have to find and kill all of the obj/debug folders now scattered everywhere because it seems MSBuild will use the obj folder if found in its default location first.

Also, why is this issue being called a problem in the "legacy project system"?  My solution/csproj files are all very much updated.  Is there some new system around the corner?  Is JSON project files coming back?

**Comment by drewnoakes** [comment]
@MikeFarrington are you using SDK-style projects? If so, then you are experiencing a different issue and should file a new ticket via Help, Feedback, Report a Problem. If you posted the link here I can make sure it gets to the right team.

If you're not using SDK-style projects (i.e. your projects have a References node instead of a Dependencies node) then you are using the legacy/traditional project type, and this GitHub issue is the cause of your problems. You might consider upgrading your project files to SDK-style in order to get the latest features, such as Directory.Build.props support.

**Comment by pokrad** [comment]
This thing was driving me insane...(and it still is..) but there is a "bad solution".
Which is better than no solution at all...

Using this addon:
https://marketplace.visualstudio.com/items?itemName=PeterMacej.ClearSolutionIntelliSenseCache

So every time i change my .props file I "Clear solution intelliSense cache" from solution explorer.
It is not fast as it reloads solution, but at least I do not have to exit visual studio and remove .suo file by hand...

Hope it helps someone :)
