### ISSUE TITLE
VS2015.3 FastUpToDate check does not respect $(PdbFile) $(SkipCopyingSymbolsToOutputDirectory) $(CopyOutputSymbolsToOutputDirectory)

### ISSUE THREAD

**Issue by 1ABAT** [dotnet/project-system#2922]
When values for $(PdbFile), $(SkipCopyingSymbolsToOutputDirectory) and $(CopyOutputSymbolsToOutputDirectory) are set in a project file, the project is never up-to-date. See uploaded example project.

[ConsoleApplication1.zip](https://github.com/dotnet/project-system/files/1413700/ConsoleApplication1.zip)

Project 'ConsoleApplication1' is not up to date. Missing output file 'C:\Dev\ConsoleApplication1\bin\Debug\ConsoleApplication1.pdb'.
------ Build started: Project: ConsoleApplication1, Configuration: Debug Any CPU ------
  ConsoleApplication1 -> C:\Dev\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by panopticoncentral** [comment]
This bug actually is about the non-CPS project system. I've opened a bug in our internal bug tracking system that tracks bugs for that project system. However, I'm leaving this open since the CPS project system also has this problem.

**Comment by panopticoncentral** [comment]
Fixed the CPS problem.

**Comment by deischi** [comment]
The problem still persists with Visual Studio 2017 Version 15.7.4 - is it supposed to be fixed for that product?

**Comment by panopticoncentral** [comment]
Are you seeing a problem in a .NET Core/.NET Standard project or a .NET Framework project? The problem should be fixed in the former, not in the latter yet.

**Comment by deischi** [comment]
The problem is with .NET framework projects. 
The example project attached originally by 1ABAT still shows the problem (or maybe a similar one):

With the PDB-path configured, build always does something.

From the .csproj file. I added the "Condition" for easier switching the configuration.
```
  <PropertyGroup>
    <PdbFile Condition="true">$(OutputPath)\pdb\$(MSBuildProjectName).pdb</PdbFile>
    <SkipCopyingSymbolsToOutputDirectory Condition="true">true</SkipCopyingSymbolsToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory Condition="true">true</CopyOutputSymbolsToOutputDirectory>
  </PropertyGroup>
```

On "Build Solution"
```
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug Any CPU ------
1>Build started 07-10-2018 08:07:04.
1>GenerateBindingRedirects:
1>  No suggested binding redirects from ResolveAssemblyReferences.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
1>CopyFilesToOutputDirectory:
1>  ConsoleApplication1 -> D:\dev\misc\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.03
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```


If I set the conditions to "false", "Build Solution" works as expected:
`========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
`
