### ISSUE TITLE
WPF and WinForms templates show up regardless of whether you are targeting WPF/WinForms

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4945]
These templates should be behind capabilities:

![image](https://user-images.githubusercontent.com/1103906/59898162-e901dd80-9432-11e9-8bd3-617528374489.png)
![image](https://user-images.githubusercontent.com/1103906/59898166-eb643780-9432-11e9-8bd7-77e3053d12fe.png)

I thought Windows Forms was already done - so I might have a old build, but that stray User Control from WPF is still present.

[AB#825237](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/825237)

**Comment by davkean** [comment]
Be sure to check VB too.

**Comment by davidwengier** [comment]
This is related to AB#825237

**Comment by jmarolf** [comment]
fixed by [AB#194273](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/194273)

**Comment by davkean** [comment]
@jjmew @davidwengier This hasn't been fully resolved, these WinForms templates still show:

![image](https://user-images.githubusercontent.com/1103906/63984148-2195f580-cb0d-11e9-9b20-2a0aec29c61a.png)

**Comment by davidwengier** [comment]
Yes, I know, trying to find where those come from. They're not in the VS repo that I can see.

**Comment by davkean** [comment]
They are located here: https://devdiv.visualstudio.com/DevDiv/_git/VS.ref_archive?path=%2Fsrc%2Fcsharp%2FWizards%2FVSZ%2Fcsharpprojectitems&version=GBmaster.

Keywords that I used; "2341 {FAE04EC1-301F-11d3-BF4B-00C04F79EFBC}" - this is the resource id and package.

This might be harder than we think as they are in the old format; vsz format which won't support capabilities.

Options:

- Move them to vstemplate
- Hide them via a manaully written Add Item template filter that explicitly calls these templates out

**Comment by davidwengier** [comment]
Thanks for that. Haven't seen .vsz before. I'm going to close this and create a new issue with above info
