### ISSUE TITLE
Project System: Advanced Compilation page has unlocalized values

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#52]
_From @davkean on April 29, 2016 18:48_

![image](https://cloud.githubusercontent.com/assets/1103906/14926261/33c1c31a-0e00-11e6-966f-fbfd1acb2d3e.png)

_Copied from original issue: dotnet/roslyn#10986_

**Comment by Giftednewt** [comment]
@davkean 
Looks like cboLanguageVersion is loading items using the GetAllLanguageVersions function here https://github.com/dotnet/roslyn-project-system/blob/235196425156a286a0aeaf3c09db4b440848580c/src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersionUtilities.vb#L15-L26 which ultimately returns the values of these constants https://github.com/dotnet/roslyn-project-system/blob/235196425156a286a0aeaf3c09db4b440848580c/src/Microsoft.VisualStudio.Editors/PropPages/CSharpLanguageVersion.vb#L10-L20

From what I can see the AdvBuildSettingsPropPage is currently the only place that uses these constants so the display values could be refactored into a resource file. I'm not sure which resource file would be best placed for these though.

The report compile time errors and debug info combos are using resource values from https://github.com/dotnet/roslyn-project-system/blob/235196425156a286a0aeaf3c09db4b440848580c/src/Microsoft.VisualStudio.Editors/PropPages/AdvBuildSettingsPropPage.resx

cboReportCompileTimeErrors and cboDebugInfo values are selected specifically based on the text value so by actually having a localized value in here that does not match up with the values from the relevant project property these will fail to select the correct combo item. I think splitting the display text from the value will solve the problem.

If you're ok with this I'll implement the changes and submit a PR

**Comment by davkean** [comment]
@Giftednewt Apologies did not see this reply. We've localized _Language Version_ in https://github.com/dotnet/roslyn-project-system/pull/1763. I'll accept a PR for this - pull them from whatever resource file is easier. We should probably correct the display info to be _Sentence case_.

**Comment by Giftednewt** [comment]
@davkean I've merged the latest code into my repo and I'm trying to apply my changes on top, but I'm unable to build the solution. I have 1470 errors in the output window, They all seem to point to missing dependencies. I've attached the build output.
[buildoutput.txt](https://github.com/dotnet/roslyn-project-system/files/864301/buildoutput.txt)

**Comment by davkean** [comment]
Ah, yes, sorry this should been documented. Right now, the VB projects are breaking restore - we have an internal build that fixes it. As a workaround, run build.cmd once from the command-line first.

**Comment by Giftednewt** [comment]
@davkean great I've made the changes and got it building now. I was looking for tests that cover this dialog, but when I open the solution in VS I can't see any files in the projects. Is this expected?

**Comment by davkean** [comment]
@Giftednewt Can you pull down this: https://github.com/dotnet/roslyn-project-system/pull/1900 and tell if that causes you to start seeing the files? The problem is that the old project system doesn't recognize some of the patterns that we're using in the repro so won't show any files.

**Comment by davkean** [comment]
We've internally got private bits installed that cause this to automatically occur - the PR I've submitted should avoid the need for that.

**Comment by davkean** [comment]
@Giftednewt I merged the the above, so pull the changes and see if that makes a difference.

**Comment by Giftednewt** [comment]
I've got the changes and the Editor project now loads but I'm still seeing nothing in the Tests project for the editor. Though looking at the files on disk there doesn't appear to be any tests for that particular property page.

**Comment by Giftednewt** [comment]
@davkean I've created a PR for the changes to the dialog. I couldn't see a way of adding tests for the dialog as nothing was showing up in VS for the unit tests project. If there is a specific way to do this let me know and I'll get them added.

**Comment by davkean** [comment]
This has been fixed in https://github.com/dotnet/project-system/commit/998b366b075bb16120952a94ec7c3242f4478367.
