### ISSUE TITLE
The code does not build on my machine

### ISSUE THREAD

**Issue by RobertvanderHulst** [dotnet/project-system#6477]
**Visual Studio Version**:Version 16.7.0 Preview 6.0

**Summary**: When I try to build the code on my machine then for some reason the .g.cs files for the xaml of the optionspages and appdesigner is not generated when building. I tried it from the commandline and inside VS.

**Steps to Reproduce**:

1.  Clone and download the repo

2. Build from the commandline

3. See several error messages that indicate that the code behind is not generated: 
   - ....DebugPageControl.xaml.cs(19,13,19,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
   - ....DebugPageControl.xaml.cs(43,28,43,56): error CS0103: The name 'dataGridEnvironmentVariables' does not exist in the current context

**Expected Behavior**:
That the code would be generated and the project would compile

**Actual Behavior**:
The code behind is not generated and the project does not compile
**User Impact**:
I can't use this.
I wanted to clone this project and build language support for our own language based on this repo. That is not possible right now...

**Comment by jjmew** [comment]
@RobertvanderHulst  We have fixed this and it should be available in the Preview soon.

**Comment by davkean** [comment]
@RobertvanderHulst We have worked around this here: https://github.com/dotnet/project-system/pull/6469. Pull the latest changes from master.

**Comment by RobertvanderHulst** [comment]
Sorry, but I have downloaded the latest code and build it from the command line with build /rebuild /diagnostic.
I am still seeing the same errors.
I am at commit e8b53fbf89d4f1ec5e770eb71bdd4c81403ce6de

**Comment by davkean** [comment]
Can you do a build /diagnostic and attach artifacts\Debug\log\Build.binlog?

**Comment by davkean** [comment]
After that a workaround is to uninstall .NET Core SDK 5.0.

**Comment by RobertvanderHulst** [comment]
David,
The binlog is attached.
[Build.zip](https://github.com/dotnet/project-system/files/5056628/Build.zip)

And I really don't like the idea of uninstalling the .Net Core SDK 5.0. We're in the middle of testing our product against .Net 5.
