### ISSUE TITLE
File Nesting: Enable the CPS file nesting implementation for all CPS projects

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#6837]
This will also entail removing all feature flag handling logic since the feature will always be enabled.

**Comment by jjmew** [comment]
@swesonga please follow up with @drewnoakes that the memory allocation issues were addressed

**Comment by drewnoakes** [comment]
I've done some work to address allocations in this area, but it still appears to be an O(N^2) algorithm. There is more work to do here. Starting with a trace seems like a good idea.

**Comment by swesonga** [comment]
Opened #7161 to track the performance impact of enabling file nesting

**Comment by ocallesp** [comment]
It can be enabled by clicking on the button 
![image](https://user-images.githubusercontent.com/510598/198158047-d6ce2a49-8d4d-4322-aeeb-e36596e116df.png)
and then select the active settings Web
![file-nesting-all-projects](https://user-images.githubusercontent.com/510598/198157875-d96ded2a-c399-4144-be40-251bd5a712d3.gif)
