### ISSUE TITLE
"View Code" and "Refresh" buttons are missing on Solution Explorer toolbar for WinForms apps

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/project-system#7765]
### Minimal Reproduction Scenario

1. Create a Winforms .Net Core application
2. In solution Explorer, focus on Form1.cs node, then observe the toolbar items at the top of solution explorer window
### Current Behavior
Missing "View Code" and "Refresh" toolbar items in Solution Explorer
![image](https://user-images.githubusercontent.com/20996271/141519237-fa120eff-f848-4a4a-8008-6ef7cd47a041.png)

### Expected Behavior
These toolbar items are there, like the result of focusing on .Net framework form
![image](https://user-images.githubusercontent.com/20996271/141519471-fb5c7ee5-5ef1-4a11-b482-190226ac7525.png)

### Test Environment
Version 17.1.0 Preview 2.0 [31911.256.main]

Have you experienced this same issue with .NET Framework designer?
**No**

Have you experienced this same issue with previous previews of VisualStudio?
Yes, also repro in 16.11, 17.0 builds

**Comment by merriemcgaw** [comment]
Originally https://github.com/dotnet/winforms-designer/issues/3947

**Comment by Tanya-Solyanik** [comment]
VS feedback ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1247129

**Comment by drewnoakes** [comment]
The refresh button is not needed for CPS projects as the tree updates automatically in response to changes.

**Comment by davkean** [comment]
The Feedback ticket should be moved over to CPS.

Refresh is by design, CPS automatically refreshes.
View Code would need investigation as to why its missing if the command itselfare enabled on the context menu.

**Comment by merriemcgaw** [comment]
Will do, thanks guys!

**Comment by Tobus2** [comment]
@merriemcgaw @drewnoakes 

Did this "View Code" button issue ever get resolved? I'm still getting the same problem a year later on the latest VS2022 14.7.2.

**Comment by drewnoakes** [comment]
@Tobus2 not that I know of. There was a work item related to the context menu which was addressed, but I don't know about the tool strip button. I can't find any ticket tracking that (and it wouldn't be in this repo anyway). Could you file a new feedback ticket for this (using _Help | Send Feedback_) and link it here? I'll make sure it's routed to the correct team internally. Thanks.

**Comment by Tobus2** [comment]
@drewnoakes  I did already (https://developercommunity.visualstudio.com/t/View-Code-button-missing-for-Net60-For/10224825) but it was immediately closed as a duplicate of this one. Can you work with that or should I submit a new one?

**Comment by Tobus2** [comment]
@drewnoakes Thanks for that.

Yes, it's still showing "private".  I've tried logging in both as the original poster (our joint work account), and as my personal account that I added the comments with, but it's the same for both of them.

**Comment by drewnoakes** [comment]
I would expect it to only show for the original poster account: https://developercommunity.visualstudio.com/user/1113894/profile

The comment just said to post on this issue instead. No action is needed on your part for now.
