### ISSUE TITLE
Retrieving file from new resource file format throws System.MissingMethodException: 'Constructor on type 'System.Byte[]' not found.'

### ISSUE THREAD

**Issue by TimSirmovics** [dotnet/project-system#9526]
### Description

When adding a resource file after upgrading Visual Studio to 17.11.0 and adding a file resource, the new Resource Explorer is used.
Then when trying to retrieve the resource using the ResourceFileName.ObjectName syntax, a `MissingMethodException` is thrown `Constructor on type 'System.Byte[]' not found.`

### Reproduction Steps

1. Create a .net8 console project
3. Add a Resources (.resx) file
4. Double click on the .resx file to open the new Resource Explorer
5. Click the + button to create a resource
6. Change the type to "File"
7. Click "Add existing file..." and select a file
8. Close the Resource Explorer.
9. The project will now fail to build with an error `MSB3822	Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references.` Add the NuGet package "System.Resources.Extensions" Version="8.0.0" to resolve the error.
10. Reference the resource file in code i.e. `var fileBytes = ResourceFileName.ObjectName`
11. Run the program, an exception will be thrown: `System.MissingMethodException: 'Constructor on type 'System.Byte[]' not found.'`

### Expected behavior

When accessing the resource file it should be returned as a byte[].

### Actual behavior

An exception is thrown: `System.MissingMethodException: 'Constructor on type 'System.Byte[]' not found.'`

### Regression?

This worked before the latest resource file / explorer changes

**Comment by melytc** [comment]
Hi, thank you for using the new Resource Explorer and for reporting this issue.

The problem is related to creating a resource of type _File_, where the assembly information isn't being saved in the resource file.

The good news is that the latest Visual Studio version includes a fix for this issue! You can download it from https://visualstudio.microsoft.com/vs/preview/. Let us know if you encounter other issues or have feedback on the new experience.

**Comment by cmierowsky** [comment]
When can we expect this fix to be in a release?

**Comment by maot01** [comment]
> When can we expect this fix to be in a release?

Would like to know this as well. Having the same issue.

**Comment by melytc** [comment]
@cmierowsky, @maot01, the fix is available in [Visual Studio 17.11.1](https://visualstudio.microsoft.com/downloads/).

**Comment by maot01** [comment]
> @cmierowsky, @maot01, the fix is available in [Visual Studio 17.11.1](https://visualstudio.microsoft.com/downloads/).

Im still getting : Constructor on type 'System.Byte[]' not found. when trying to access a File saved in Resource

Like such :

var test = Resource.MyFile;

![image](https://github.com/user-attachments/assets/75ce48fd-5d99-4dc0-96f0-e85958a665b9)

**Comment by melytc** [comment]
I wonder if I am missing something in here.

I followed the repro steps and I was able to run the program with no exception:
![image](https://github.com/user-attachments/assets/943ff68d-716e-4c9e-b024-eae573ab9000)

I notice that for me, the file is being saved as a `System.String`. If I open the Managed Resource Editor, the legacy experience (Open With > Managed Resource Editor(legacy)), it is also saved as a `System.String`.

If you try to change the resource type in the XML editor (Open With > XML (Text) Editor) from Byte[] to System.String, does exception still occur?

**Comment by maot01** [comment]
> I wonder if I am missing something in here.
> 
> I followed the repro steps and I was able to run the program with no exception: ![image](https://private-user-images.githubusercontent.com/8518253/361528347-943ff68d-716e-4c9e-b024-eae573ab9000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDg1NDgsIm5iZiI6MTcyNDc0ODI0OCwicGF0aCI6Ii84NTE4MjUzLzM2MTUyODM0Ny05NDNmZjY4ZC03MTZlLTRjOWUtYjAyNC1lYWU1NzNhYjkwMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMDg0NDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM4M2U2YWIyY2I2ODRmOTBmZjhmY2Y4YjI3MWZlZTQzNjkxOWZmNzFlNTNmOWFiMWRjOWY1N2RmM2ZiYjFmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VAPO8ZeHigAJSs0wF5kHorEPmZeWO56CqVhRdtP6k9A)
> 
> I notice that for me, the file is being saved as a `System.String`. If I open the Managed Resource Editor, the legacy experience (Open With > Managed Resource Editor(legacy)), it is also saved as a `System.String`.
> 
> If you try to change the resource type in the XML editor (Open With > XML (Text) Editor) from Byte[] to System.String, does exception still occur?

This does not work. I have attached an .exe file and that gets stored as byte[]. When trying to force this type to a string it results in "Resource was of type 'System.String' instead of String - call GetObject instead."

I guess in your case its saved as string since its a .cs file you have attached. In my case I need to be able to embed a .exe and be able to retrieve it at a later point.

![image](https://github.com/user-attachments/assets/ab049d91-ecd9-433d-909e-488437ba9745)

**Comment by melytc** [comment]
Thanks for the clarification, @maot01. I can see the error now; I'll investigate this further and keep this thread updated.

**Comment by melytc** [comment]
A fix for this issue has been internally implemented and is being prepared for release, where we treat text files as `System.String` and other files, like .cs and .exe, as `System.Byte[]`. Thanks again for bringing this up! We’ll update you once it becomes available for download.

**Comment by maot01** [comment]
Has the fix to this issue been released yet? Now it seems with the current version of VS community (17.11.5) I cannot even attach .exe files in the new resource manager. Funny thing, it works perfectly to import them using the legacy solution (and then I can actually read the file). This seems a bit embarrassing at this point... 😅

**Comment by Perpete** [comment]
I also have the same problem with adding fonts.
There are also other problems especially with adding images.
I have to correct the content of the resource files .resx and .Designer.vb to have a correct operation.

Will we soon have a new version of visual studio (17.11.6) with the essential fixes of the resource explorer?

**Comment by colinb2048** [comment]
Still having this problem in 17.12.1 with adding image files to a new resx file. Adding ,mscorlib fixes this as @ericstj suggested

**Comment by TimSirmovics** [comment]
Any updates on this?
